{{- $hasAnalytics := dict }}
{{- range .Values.dashboards }}
{{- if eq .namespace "observability-analytics" }}
{{- $_ := set $hasAnalytics "found" true }}
{{- end }}
{{- end }}
{{- if hasKey $hasAnalytics "found" }}
apiVersion: v1
kind: Namespace
metadata:
  name: observability-analytics
  labels:
    app: {{ template "coohelm.name" . }}
    chart: {{ template "coohelm.chart" . }}
    release: {{ .Release.Name }}
{{- end }}
